### PR TITLE
Issue 22 update flexdashb

### PR DESCRIPTION
**Pull request by fileunderwater**
@mskyttner Can you review this? 
The purpose is to make the flexdashboard only dependent on the amb_tableX functions. I have also added some placeholder graphs to the dashboard, and merged the citation tabs. 

There is a new parameter defined in the header which can be used to do a parameterized knit on unit_code. 

The aim is however not to fix all the formatting in the flexdashboard. One thing we should look at is a way to create automated number formatting and pretty print of tables (now too many digits in most tables).

### CODE REVIEW

**Comment by mskyttner** [comment]
@fileunderwater :+1: I suggest using the embedded external data, and had to comment out the private data part (embedding publication list) because my connection was slow. I was able to build the dashboard quickly after that change. I suggest this be merged.

**Comment by mskyttner** [comment]
@fileunderwater :+1: I suggest using the embedded external data, and had to comment out the private data part (embedding publication list) because my connection was slow. I was able to build the dashboard quickly after that change. I suggest this be merged.

**Comment by fileunderwater** [comment]
@mskyttner Do you mean that it should be re-written before merging (to use cached data) or merged as-is. I noticed the new functions for external data after making the pull request, but the master was pulled into the branch before the pull request, so everything is there.

**Comment by mskyttner** [comment]
@fileunderwater 598f4ac which I added to this PR contains a switch to either use bundled external data (originating from `abm_public()`) or a live db connection, it also has a change to use the KTH color palette. I suggest this to be merged as-is, if you're ok with those changes.

**Comment by fileunderwater** [comment]
@mskyttner Oh, I missed your additions and will test and merge if everything works for me as well. Good with the data source switch!
Does the addition of library(scales) require any addition to kontarion (i.e. to install the package to the server)?

**Pull request merged**
