### PR TITLE
Abm test

### PR DESCRIPTION
**Pull request by fileunderwater**
@agnepagne Can you check if the tests for the abm-tables look ok? A specific unit for the test is set in the beginning. The test can be run with ctrl+shift+t if testthat is installed and loaded.

Currently the test for the Diva table (abm_table1) is failing on WoS-coverage, which seems correct (i.e. not due to an incorrect test) and has to be fixed .

### CODE REVIEW

**Comment by fileunderwater** [comment]
Noticed that the Travis build fails, but this is maybe just due to the failed test(?). Travis builds seem to have passed up to the later commits, when the Diva/volume table was added (where the comparison currently fails).

**Comment by fileunderwater** [comment]
Failed test now resolved in this branch, by modification in /R/abm.R
This will also resolve Issue #18

**Comment by fileunderwater** [comment]
Travis build fail is probably due to:

`Error: processing vignette 'intro.Rmd' failed with diagnostics:
   no such table: t_diva
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
Calls: <Anonymous> ... with_envvar -> force -> do.call -> <Anonymous> -> throw
Execution halted

Exited with status 1.`

This is the exit status when running a local check (crtl+shift+e). I don't see the reason yet though. T_diva is there, and nothing here has been changed in this branch.

**Comment by mskyttner** [comment]
@fileunderwater sure, I'll take a look, from your comment and the error I'll start with double-checking the capitalization of the table name ("no such table: t_diva" and "T_diva" is there) in case that comes into play.

**Comment by fileunderwater** [comment]
It is ’t_diva’, which is in Bibmon. The capital T was just because of punctuation. I now tried building the vignettes specifically (devtools::build_vignettes) and this fails with the same error. 
Running ‘abm_tab1()’ in terminal works though, which is accessing the same table (this is called in intro.Rmd as well, which probably(?) is causing the error)

**Comment by fileunderwater** [comment]
@mskyttner I found the problem now I think. It is this call in intro.Rmd which is causing the problem:

` # get data but explicitly specify the data source 
 src1 <- abm_tab1(con = con_bib("mssql"))
 src2 <- abm_tab1(con = con_bib("sqlite"))
 
 # are the results the same?
 identical(src1, src2)
 
 # what about performance?
 bench_time(abm_tab1(con = con_bib("mssql")))
 bench_time(abm_tab1(con = con_bib("sqlite")))`

I'm guessing it is the retrieval of t_diva using sqlite which is failing. However, when commenting this out, the same script is giving an error from:
`# search Active Directory using an account name, return first 10 rows
ad_search("markussk", "accountname") %>% head(10) %>% kable()

# search AD using a KTH identifier, same result, so return first row only
ad_search("u1o2ujjd", "kthid") %>% head(1) %>% kable()

# default if search_type is not specified is to use KTH id
#ad_search("u1o2ujjd")

# display memberships for an Active Directory user with a specific KTH id
ad_search("u1o2ujjd") %>% 
  filter(str_starts(key, "ug.*Affiliation")) %>% 
  kable() 

# function to return account name for a given KTH id
ad_accountname_from_kthid <- function(x)
  ad_search(x) %>% filter(key == "sAMAccountName") %>% pull(value)

# use the above fcn to get the account name for a given kth id
ad_accountname_from_kthid("u1o2ujjd")

# several kth identifiers can be processed, for example:
kthids <- 
"u1kzf1xh
u1g9umtq
u1jr9fll 
u1ygqmuy
u13bp6vd
u18qe64m" %>% 
read_lines()

# display memberof entries beginning with "ug" for a given identifier
ad_search(kthids[4]) %>% 
ad_memberof() %>% 
filter(str_starts(memberof, "aff")) %>%
kable()
`
Maybe caused by the user info in the beginning? I haven't looked at the code carefully though. Commenting out this as well makes it possible to check and build vignettes without errors.

**Comment by mskyttner** [comment]
@fileunderwater the LDAP issue is probably due to "LDAP_USER, LDAP_PASS, LDAP_HOST and LDAP_BASE in your .Renviron"?

I pulled the latest changes into this branch from the master branch and made a change to the vignette where it calls `db_sync()` to get some data into the sqlite3 db (initial, run once).

I also added a flag to be able to skip the abm tests when running in the cloud. The checks then seems to pass.

**Comment by mskyttner** [comment]
@agnepagne @fileunderwater if you're happy with this, please merge, other issues discovered during work on this issue can be logged separately

**Pull request merged**
