### PR TITLE
Use 13 colors for DiVA graph since there are 13 publication types.

### PR DESCRIPTION
**Pull request by agnepagne**
Maybe there is a better color to combine the 12 color "Set3" with, this one at least makes it visible in the graph that KTH has patents at all.

### CODE REVIEW

**Comment by agnepagne** [comment]
Nothing more to add att the moment, merge if you want @fileunderwater.

Good idea to include palettes the way we want them in the styling package later!

**Comment by fileunderwater** [comment]
@agnepagne I'll try rerunning the checks with Travis, just to see if they has fixed the upstream issue, and will merge afterwards

**Comment by fileunderwater** [comment]
@agnepagne This is giving a Travis build error (warning) from RColorBrewer:

`* checking dependencies in R code ... WARNING
'::' or ':::' import not declared from: ‘RColorBrewer’`

**Comment by agnepagne** [comment]
Gröna bockar från Travis, mergear.

**Pull request merged**
