### PR TITLE
Update ABM data after last org changes.

### PR DESCRIPTION
**Pull request by agnepagne**
This is hopefully the final ABM data for 1.0.

### CODE REVIEW

**Comment by agnepagne** [comment]
Added tests of ABM tables for all units in the testthat folder. They all pass!

The individual researcher tables take 15-20 minutes to test on my laptop. There might be more efficient ways to compare several individuals simultaneously, but since this is more or less a one-off test I think we can live with that time.

**Comment by agnepagne** [comment]
...and now Travis seems to have problems again, and does not even start to test the package. Fail message is:

> The command "eval sudo apt-get install -y --no-install-recommends build-essential gcc g++ libblas-dev liblapack-dev libncurses5-dev libreadline-dev libjpeg-dev libpcre3-dev libpng-dev zlib1g-dev libbz2-dev liblzma-dev libicu-dev cdbs qpdf texinfo libssh2-1-dev devscripts gfortran " failed 3 times.
> The command "sudo apt-get install -y --no-install-recommends build-essential gcc g++ libblas-dev liblapack-dev libncurses5-dev libreadline-dev libjpeg-dev libpcre3-dev libpng-dev zlib1g-dev libbz2-dev liblzma-dev libicu-dev cdbs qpdf texinfo libssh2-1-dev devscripts gfortran" failed and exited with 100 during .
> Your build has been stopped.

**Comment by agnepagne** [comment]
OK, the Travis tests now seem to fail on package test instead. Have to check this tomorrow.

**Comment by fileunderwater** [comment]
I'm getting a testthat failure on one ID:
   `nanodbc/nanodbc.cpp:1617: 08S01: [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure 
<SQL> 'SELECT *
FROM "masterfile"
WHERE ("Unit_code" IN ('u1crxwo0'))'`

Ska se närmare vad det kan bero på

**Comment by mskyttner** [comment]
@fileunderwater I was able to run the steps in dev.R without any exceptions (.data and column name "-Inf") just FYI. 

Could that issue somehow be related to this change that I needed to do before xmas due to getting SQL Server timeouts in the ref environment? https://github.com/KTH-Library/bibliomatrix/blob/master/R/db.R#L9

If so, running `db_sync()` and overriding stale data in sqlite3 db might make a difference? I updated the "dev.R" file to do so, in case that could play into that issue you were seeing...

**Comment by fileunderwater** [comment]
@mskyttner I can also manage to run e.g. public_data.R without errors after the sync you suggest.
However, I still cannot get the local instance of the API to work together with the shiny app (API running in console and shiny through RStudio), and for many organization choices I only get "Not found" in the shiny output. Here it doesn't matter if I choose pre-rendered or not. However, results for some organizations are shown (so they are obviously cached), incl some of the new ones (after last org change). 

However, I think that this is a separate issue from this specific pull request, and possibly/probably me not having a full overview of all the moving parts. Creating the individual dashboards works fine (for the new organizations) as well as the new tests that have been written. So I'm merging this pull request now.

@agnepagne

**Pull request merged**
