### PR TITLE
Issue #1, #2 and #3

### PR DESCRIPTION
**Pull request by mskyttner**

### CODE REVIEW

**Comment by mskyttner** [comment]
@agnepagne does this work better on Windows?

**Comment by agnepagne** [comment]
@mskyttner the tests in test-db.R both give below message, not sure if that is a problem.

> warning: sync for all db tables work
> Couldn't set synchronous mode: database is locked
> Use `synchronous` = NULL to turn off this warning.

The LDAP stuff in intro.Rmd runs but gives no result as far as I can see, assuming it should look something like
> Key    Value
> xxx  u1abcdef
> yyy Department of Z

I only get
> Key    Value

Forced reading of .Renviron on Win seems functional.

**Comment by mskyttner** [comment]
@agnepagne tried in 8eb6158 to add a workaround for the nul bytes issue in the LDAP query on Win but haven't tested it on Win

**Comment by mskyttner** [comment]
@agnepagne 

for me, running this:

```r
ad_search("markussk", "accountname") %>% filter(key %in% c("protocolSettings:", "objectGUID:"))
```
returns this:

```
 key               value                                       
  <chr>             <chr>                                       
1 protocolSettings: SU1BUDTCpzHCp8KnwqfCp8KnwqfCp8KnwqfCp8Knwqc=
2 protocolSettings: UE9QM8KnMMKnwqfCp8KnwqfCp8KnwqfCp8KnwqfCpw==
3 objectGUID:       XeBoMV9snkagKIVCDv7WdA== 
```                   
Note the `:` and what seems to be maybe base64 encoded strings...

**Comment by mskyttner** [comment]
@agnepagne what does win say about this if you use it in the `ldap_search_curl` fcn:

```r
res <- curl_fetch_memory(query, handle)
raw <- readBin(res$content, "raw", length(res$content))
message("Guess encoding for content:")
print(readr::guess_encoding(raw))
mytext <- iconv(readBin(raw, character()), from = "ASCII", to = "UTF-8")
```

**Pull request merged**
