### PR TITLE
Issue 5

### PR DESCRIPTION
**Pull request by agnepagne**
Some changes intended to deal with Issue #5, which is unfortunately not very specific.

### CODE REVIEW

**Comment by agnepagne** [comment]
This PR introduces abm_tableX_display functions, intended to be used as the last step for displaying ABM tables online with reasonable field names and formats (though they don't really do anyting yet) leaving the ordinary abm_tableX tables for data extraction only (may be useful also for dashboard indicators and graphs).

This may not be a great idea after all, and has the unfortunate side effect that the ordinary abm_tableX functions will not do dbDisconnect(). Not sure if that is a big problem, I guess we will just end up with ghost connections that will eventually be closed by the DB server.

I would like to merge this anyway, because there are a some other small fixes in there. The problem with just restoring abm_tableX as they were is that this makes it impossible to select a connection parameter in abm_dash_indices().

The database connection situation should improve when we address Issue #13.

**Comment by mskyttner** [comment]
@agnepagne sounds great I'm taking a look now

**Comment by mskyttner** [comment]
:+1: for me the local build and check worked (Ctrl-Alt-E and Ctrl-Alt-T). I also ran the `pkgdown::build_site()` to update the web docs.

**Comment by agnepagne** [comment]
Merged this into a local branch based on Issue-13 and intend to merge that branch with Issue-13 after resolving conflicts and only keeping the good stuff from Issue-5. Therefore, we can skip pulling this to master.

**Pull request closed without merging**
