### PR TITLE
Issue24 intervals

### LINKED ISSUE #24: Test fails when getting private data for specific kthid
This test fails when the last kthid in the list is added:

https://github.com/KTH-Library/bibliomatrix/blob/master/tests/testthat/test-abm-private-data.R#L19

It could be related to users with few data records and the `sliding_intervals()` function.

### PR DESCRIPTION
**Pull request by agnepagne**
Intends to fix #24 by explicitly telling the abm functions what the first and last "global" years of analysis are. Thereby, they will not rely on what publication years are available for specific unit_codes. At this point, analysis_start and analysis_stop are set to 2012 and 2018 as default, meaning that everything will work without further changes for ABM 2019.

If we use these functions for other projects later, we will have to give analysis years to the functions (or give a project_id, see Trello card about time stamping masterfile, which might be a better long-term solution).

### CODE REVIEW

**Comment by fileunderwater** [comment]
Yes, good idea and a clear problem now. Slightly related is also to decide what the “default” periods used in the dashboard overview should be, ie last year/period or total. Also should they be the same for orgs and individual researchers. 

I will try to review and test the code tomorrow.

**Comment by agnepagne** [comment]
> Slightly related is also to decide what the “default” periods used in the dashboard overview should be

Yes, maybe we should use the entire time period for individuals. Or for all kinds of units. 

Also, in the current solution there is no information about what time period the dashboard numbers cover. It would be great if we could show that.

**Comment by fileunderwater** [comment]
The branch seems to run fine with no conflicts. One thing I thought about though; shouldn't we put "abm defaults" (i.e. start/stop years here) in a particular function or a named list? So that these can be called in all the functions, but also updated in one place. At the moment, the years are hard-coded at each function call. 

I started testing some options, but am a bit unsure about where to best place this. In abm.R as a function, as a named list that is accesible globally, or something else?

@agnepagne

**Comment by agnepagne** [comment]
Yes, it is probably not optimal, and maybe a little dangerous, to hardcode first/last year defaults.

I am also unsure about where to put global stuff. One idea, more detailed in the Trello card "Masterfile - märk upp 2019 - tidsstämpla", is to attach a project_id to all rows in masterfile and keep info (like first/last year) about all project_id:s in a separate table. Then we can set project_id in the beginning of an app (or flexdashboard or analysis file or whatever) and either let the functions take a project_id as input or (as @fileunderwater suggests) use a function abm_defaults that fetch needed info from the info table.

Anyway, since current solution should work for ABM 1.0, we have time to discuss and rearrange code later.

**Comment by fileunderwater** [comment]
But isn't it possible to just put `abm_defaults<- list(analysis_start = 2012, analysis_stop = 2018)` at the top of abm.R right now, and then call this as:
    `abm_table1 <- function(con = con_bib(), unit_code, analysis_start = 2012, analysis_stop = 2018){...`

I pushade a sugestion for this "default solution", which however only contains start and stop years at the moment.

Then there is at least a starting point for a place to put deafults, and not individual definitions of the same years in multiple locations

**Pull request merged**
